### ISSUE TITLE
可以设置屏蔽返回键么

### ISSUE THREAD

**Issue by Swordce** [weavey/NormalSelectDialog#5]

**Comment by weavey** [comment]
2.0版本已开放方法将Dialog对象返回，一些比较少用的属性可直接getDialog()自行设置，屏蔽返回键可参考：

            dialog.getDialog().setOnKeyListener(new android.content.DialogInterface.OnKeyListener() {

            @Override
            public boolean onKey(android.content.DialogInterface dialog, int keyCode, KeyEvent
                    event) {
                if(keyCode==KeyEvent.KEYCODE_BACK){

                    return true;
                }

                return false;
            }
        });
